apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
      - name: telemetry-api
        image: <my-repo>/telemetry-api:latest
        ports:
        - countainerPort: 8080
--
apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-service
spec:
  type: LoadBalancer
  selector:
    app: telemetry-api
  ports:
    - port: 80
      targetPort: 8080